### ISSUE TITLE
Changing the color in the footer

### ISSUE THREAD

**Issue by Phantast01** [madi-nuralin/material#3]
Hello, Dear Developer! I really like your theme. There is one question about how to change the footer background? Thank you in advance!

**Comment by madi-nuralin** [comment]
Hi @Phantast01, thank you
For that moment it is not customizable through plugin theme settings panel, while you can manually change it through manipulation of ```material/templates/components/footer.tpl``` file. Btw, I'll add this functionality to the becoming minor release of the plugin, so that you could just change footer colour from admin panel.

**Comment by Phantast01** [comment]
Thank you very much! Please tell me when the plugin update is planned? Once again I express my gratitude!

**Comment by madi-nuralin** [comment]
Actually within a 1-1,5 month, if there are enough fixes to release.
