### ISSUE TITLE
Section Block

### ISSUE THREAD

**Issue by frankycalo** [madi-nuralin/material#4]
Hi, 
nice theme,
but there is no blocks zone?

**Comment by madi-nuralin** [comment]
Hi, thanks
Yes, you're right, it is not supported by the theme currently.

**Comment by madi-nuralin** [comment]
@frankycalo, I'm sorry to have missed this for so long! For now, section blocks are available by last release, you can check https://github.com/madi-nuralin/material/releases/tag/v2_0_1-0

**Comment by ict4iq86** [comment]
hello
How i can editing the theme?

**Comment by madi-nuralin** [comment]
Hi,
I think you meant the theme overall.

In order to make your local changes, you can follow instruction in pkp/ojs documentation here https://docs.pkp.sfu.ca/dev/plugin-guide/en/templates. So, material design was implemented in accordance with this official instruction.

Btw, what kind of change you wanted to perform ?,  so that I can help with an advise in detail)

If you want to contribute to this material theme you are welcome to push merge requests or patches.
